# Generated by Django 3.2.3 on 2021-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210523_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kr_name',
            field=models.CharField(max_length=40),
        ),
    ]
